apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "<CHARTNAME>.fullname" . }}
  labels:
{{ include "<CHARTNAME>.labels" . | nindent 4 }}
data:
  application.properties: {{ toYaml .Values.applicationProperties | nindent 4 }}
