apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
{{ include "<CHARTNAME>.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /{{ or $.Values.ingress.path  $.Release.Name }}/(.*)
            backend:
              serviceName: {{ include "<CHARTNAME>.fullname" $ }}
              servicePort: 8080
