environment: local

image:
  tag: latest
  repository: sybrenbolandit/<CHARTNAME>
  pullPolicy: Always

metrics:
  enabled: false

ingress:
  path: spring

autoscaling:
  enabled: false

livenessProbe:
  enabled: false

readinessProbe:
  enabled: false

resources: {}

application.properties: |
  TODO: add you application properties here
